### PR TITLE
[Automation] Update go matrix

### PR DESCRIPTION
**Pull request by chizhg**
- go matrix updates

Update the go matrix in the CI workflows to include the new supported runtimes.

Auto-generated by https://github.com/chizhg/serverless-runtimes-automation/actions/runs/4720039484

### CODE REVIEW

**Comment by KaylaNguyen** [comment]
We no longer support go 1.11: https://cloud.google.com/functions/docs/runtime-support#go. Did you mean go 1.12?

**Comment by chizhg** [comment]
> We no longer support go 1.11: https://cloud.google.com/functions/docs/runtime-support#go. Did you mean go 1.12?

The list is returned by the below command, and the automation flow use it to create the PR change:

```
$ gcloud functions runtimes list --format="value(NAME)" --project=gae-runtimes-private --region=us-west1 | grep ^go | tr '\n' ' ' | xargs
go111 go113 go116 go118 go119 go120
```

Do you know why it returns go111 instead of go112?

**Comment by KaylaNguyen** [comment]
Ah, thanks for pointing that out! Let me look into this.

**Comment by KaylaNguyen** [comment]
go111 shows up as deprecated. Let's skip this version for go matrix here.

```
→ gcloud functions runtimes list
Suggest using `--region us-west1`
NAME       STAGE       ENVIRONMENTS
go111      DEPRECATED  1st gen
go113      GA          1st gen, 2nd gen
go116      GA          1st gen, 2nd gen
go118      GA          1st gen, 2nd gen
go119      GA          1st gen, 2nd gen
go120      GA          1st gen, 2nd gen
```

**Pull request closed without merging**
